### ISSUE TITLE
Swift 12.1 update

### ISSUE THREAD

**Issue by coolice2015** [jayliew/bluetoothPolarH7Swift#2]
May I ask if you could update it to the latest Swift please if your time allows? BIG thank you in advance!

**Comment by jayliew** [comment]
I'm afraid I'm currently swamped and won't be able to get to it in a timely manner. It's not too complicated though. The file you want to look at is this: https://github.com/jayliew/bluetoothPolarH7Swift/blob/master/bluetoothPolarH7/ViewController.swift
